### ISSUE TITLE
[Issue/Bug] Error while automatically handling spam protection

### ISSUE THREAD

**Issue by JjTheHusky** [GilbertGobbels/GAwesomeBot#37] opened 2017-01-25 21:54 UTC
https://hastebin.com/opimuyotaz.sql

Updated, this causes the bot to crash.

**Comment by KingDGrizzle** [comment] 2017-01-25 22:01
Suggestion: Please use hastebin for errors, as its cleaner to see 😛

**Comment by JjTheHusky** [comment] 2017-01-25 22:03
Updated.

**Comment by KingDGrizzle** [comment] 2017-01-25 22:08
Code snip that breaks: https://hastebin.com/odurojeyul.vbs

**Comment by HilbertGilbertson** [comment] 2017-02-10 02:37
Duplicate of #64 - or should I say that issue was a duplicate of this one. Already fixed in #65.

**Closed by HilbertGilbertson** 2017-02-10 02:37 UTC
Labels: bug, duplicate, high priority, V4 WIP source

**Comment by KingDGrizzle** [comment] 2017-02-10 07:04
Yet again, you dun goofed
It as nothing to do with that
Its the hey, your spamming and it can't save the spamDocument of the channelDocument of the serverDocument

**Comment by KingDGrizzle** [comment] 2017-02-10 07:05
Yet again, I just guufed
Nevermind
