### ISSUE TITLE
[Bug] !messages only counts commands

### ISSUE THREAD

**Issue by mistmurk** [GilbertGobbels/GAwesomeBot#23] opened 2017-01-22 23:38 UTC
Currently the messages command is only tracking how many times a user uses the bot commands, while it should track total messages.

**Comment by KingDGrizzle** [comment] 2017-01-30 04:50
I'll look into this very soon, I think I know why its bugged.

**Comment by HilbertGilbertson** [comment] 2017-02-10 02:31
Anyone made any progress on this? @mistmurk Am I imagining it or did you say on the Discord the other day that you might have made some progress on this issue. @KingDGrizzle did you find out the cause?

**Comment by KingDGrizzle** [comment] 2017-02-10 07:02
Couldn't tell. Looked through the code I thought will only trigger when running a command, but the thing to add to the total count is **OUTSIDE** the command processing.

**Comment by mistmurk** [comment] 2017-02-10 07:03
The issue is currently the database is only saved under certain conditions.  If you save after every message the command works. However, I haven't been able to test the performance hit, so I didn't make a pull request yet.

**Comment by KingDGrizzle** [comment] 2017-02-10 07:05
Could you send us the code snip so we can test it?

**Comment by KingDGrizzle** [comment] 2017-02-25 07:47
Could you give us the code snip, or any progress info @mistmurk?

**Comment by KingDGrizzle** [comment] 2017-03-06 21:09
@rgiyf kindly gave us a nice and clean solution for this issue, in the magical #100 

Marked as closed, as that is perfectly what we needed

**Closed by KingDGrizzle** 2017-03-06 21:09 UTC
Labels: bug, command, V4 WIP source
