### ISSUE TITLE
IMDB Command Broken

### ISSUE THREAD

**Issue by Kyle2000** [GilbertGobbels/GAwesomeBot#179] opened 2017-06-09 15:00 UTC
The IMDB command always returns `Nothing found on IMDB`. I think it is an error with the API GAB is using.

**Comment by TTtie** [comment] 2017-06-09 15:03
Confirmed to not be working
![img](https://owo.solutions/fc6d65.png)

**Comment by KingDGrizzle** [comment] 2017-06-09 16:36
Its not a bug, currently we'd need to pay for an license key

**Comment by TTtie** [comment] 2017-06-09 18:09
>we'd need to pay for an license key

truedat

**Comment by Minionjosh** [comment] 2017-06-09 18:13
How much is a licence key tho?

**Comment by KingDGrizzle** [comment] 2017-06-09 18:24
Around 1$, or wait till they go back to free, as from what the Patreon said, they will be working on rate limitations and such

**Comment by Minionjosh** [comment] 2017-06-09 18:26
...... could i throw that dollar to give a licence key to make it work .... ;)

**Comment by KingDGrizzle** [comment] 2017-06-09 18:33
I'd suggest asking Gilbert, but remember. Its per-month or till the API is finally free

**Comment by Minionjosh** [comment] 2017-06-09 18:35
1 dollar a month is nauthing

**Comment by Minionjosh** [comment] 2017-06-09 19:41
..... Gilbert ..... You now need to do some work ...

**Comment by KingDGrizzle** [comment] 2017-06-10 08:18
I'll move this to #178, so closing

**Closed by KingDGrizzle** 2017-06-10 08:18 UTC
