### ISSUE TITLE
[Bug] Strike command causes internal error

### ISSUE THREAD

**Issue by wasdennnoch** [GilbertGobbels/GAwesomeBot#523] opened 2019-04-23 18:34 UTC
**Please describe the problem you are having in as much detail as possible:**
Using the strike command without setting up a modlog channel results in an internal error related to a missing modlog channel.
![screenshot of error message](https://i.imgur.com/4V1SQOU.png)

- [x] The problem happens on the official GAwesomeBot
- Priority this issue should have – please be realistic and elaborate if possible:
  - [ ] Low (Only partially affects the usage of a feature or command)
  - [ ] Medium (Affects the full usage of a feature or command)
  - [x] High (Prevents the full usage of a feature or command)

**Comment by wasdennnoch** [comment] 2019-04-24 19:05
It appears that even after setting up a modlog channel the strike command does not work and throws another error, rendering the strike command completely unusable.

![screenshot of error message](https://i.imgur.com/Oz9zg6Y.png)

**Comment by Gilbert142** [comment] 2019-04-24 21:21
@wasdennnoch I can't reproduce that second error in testing. Will follow up with user to find out more.

First error should indeed be ignored by commands for which ModLog isn't essential. Will fix!

**Comment by Gilbert142** [comment] 2019-04-24 21:33
First error fixed, will keep issue open in relation to second error.

**Comment by Gilbert142** [comment] 2019-07-23 23:33
Fixed in indev branch.

**Closed as completed by Gilbert142** 2019-07-23 23:33 UTC
Labels: reason: Bug, priority: Critical, target: Commands, s: Fixed, s: In Progress
