### ISSUE TITLE
MotD loop / impossible to cancel

### ISSUE THREAD

**Issue by ShinyArmor** [GilbertGobbels/GAwesomeBot#199] opened 2017-09-19 15:29 UTC
After creating a new MotD it becomes impossible to cancel it. Once it's created it's there to stay and will continue to loop even if you disable the MotD functionality it'll still keep spamming using the original settings. Furthermore if you disable an old message and create a new one it'll spam both of them. I currently have 3 MotD running on a testing server and I'm unable to cancel any of them.

**Comment by TTtie** [comment] 2017-09-19 15:33
We know of this issue and it should be fixed in 4.1, hopefully.

**Comment by vladfrangu** [comment] 2017-09-19 15:34
First, this is a dupe of #137, which has been fixed in the rewrite.

Secondly, if you are self hosting, just make sure the MOTD is off and restart your bot. Otherwise, if you are using the GAwesomeBot instance, you'll have to unfortunately mute the bot.

**Closed as completed by vladfrangu** 2017-09-19 15:34 UTC
Labels: s: Fixed, s: Duplicate
